# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: tags/
    weight: 20
  - name: Publications
    url: uses/
    weight: 30
