# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: research/
    weight: 20
  - name: Uses
    url: uses/
    weight: 30
  - name: Publications
    url: publications/
    weight: 40
